# Generated by Django 5.0.6 on 2024-06-17 15:07

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='newuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='name',
        ),
        migrations.AddField(
            model_name='newuser',
            name='favourite_facility',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='newuser',
            name='home_address',
            field=models.TextField(blank=True),
        ),
    ]
