# Generated by Django 5.0.4 on 2024-05-22 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schulen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('objectid', models.IntegerField(null=True)),
                ('typ', models.IntegerField()),
                ('art', models.CharField(max_length=255)),
                ('standorttyp', models.CharField(blank=True, max_length=255, null=True)),
                ('bezeichnung', models.CharField(max_length=255)),
                ('bezeichnungzusatz', models.TextField(blank=True, null=True)),
                ('kurzbezeichnung', models.CharField(max_length=255)),
                ('strasse', models.CharField(max_length=255)),
                ('plz', models.CharField(max_length=10)),
                ('ort', models.CharField(max_length=255)),
                ('telefon', models.CharField(max_length=20)),
                ('fax', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('profile', models.TextField(blank=True, null=True)),
                ('sprachen', models.TextField(blank=True, null=True)),
                ('www', models.URLField(blank=True, null=True)),
                ('traeger', models.CharField(max_length=255)),
                ('traegertyp', models.IntegerField()),
                ('bezugnr', models.CharField(max_length=255, null=True)),
                ('gebietsartnummer', models.IntegerField()),
                ('snummer', models.IntegerField()),
                ('nummer', models.IntegerField()),
                ('globalid', models.CharField(max_length=255)),
                ('creationdate', models.DateTimeField()),
                ('creator', models.CharField(max_length=255)),
                ('editdate', models.DateTimeField()),
                ('editor', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('coordinates', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
