# Generated by Django 5.0.4 on 2024-05-26 23:10

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_alter_schulen_coordinates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kindertageseinrichtungen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('objectid', models.IntegerField(null=True)),
                ('traeger', models.CharField(max_length=255)),
                ('bezeichnung', models.CharField(max_length=255)),
                ('kurzbezeichnung', models.CharField(max_length=255)),
                ('strasse', models.CharField(max_length=255)),
                ('strschl', models.CharField(max_length=10)),
                ('hausbez', models.CharField(max_length=10)),
                ('plz', models.CharField(max_length=10)),
                ('ort', models.CharField(max_length=255)),
                ('hort', models.CharField(max_length=255)),
                ('kita', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, null=True)),
                ('telefon', models.CharField(max_length=20)),
                ('fax', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('barrierefrei', models.CharField(max_length=255)),
                ('integrativ', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
        ),
    ]
