# Generated by Django 5.0.4 on 2024-05-26 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_kindertageseinrichtungen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kindertageseinrichtungen',
            name='telefon',
            field=models.CharField(max_length=50),
        ),
    ]
